### ISSUE TITLE
2.2.0 Translate not working fo rme

### ISSUE THREAD

**Issue by NewMember12345** [jvlflame/Javinizer#158]
```
Javinizer ./200GANA-1864/200GANA-1864.1080p.2048.mp4 -SettingsPath './jvSettings.json'
Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     | Traceback (most recent call last):

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |   File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translate_new.py", line 7, in <module>

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |     translation = translator.translate(sys.argv[1], dest=sys.argv[2])

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |   File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182, in translate

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |     data = self._translate(text, dest, src, kwargs)

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |   File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78, in _translate

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |     token = self.token_acquirer.do(text)

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |   File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194, in do

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |     self._update()

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |   File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62, in _update

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     |     code = self.RE_TKK.search(r.text).group(1).replace('var ', '')

Write-Error: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Public/Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     | AttributeError: 'NoneType' object has no attribute 'group'
```

I'm running settings file:

`cat jvSettings.json
{
    "throttlelimit": 3,
    "location.input": "",
    "location.output": "",
    "location.thumbcsv": "",
    "location.genrecsv": "",
    "location.uncensorcsv": "",
    "location.historycsv": "",
    "location.log": "",
    "scraper.movie.aventertainment": false,
    "scraper.movie.aventertainmentja": false,
    "scraper.movie.dmm": false,
    "scraper.movie.dmmja": false,
    "scraper.movie.jav321ja": false,
    "scraper.movie.javbus": false,
    "scraper.movie.javbusja": false,
    "scraper.movie.javbuszh": false,
    "scraper.movie.javlibrary": false,
    "scraper.movie.javlibraryja": false,
    "scraper.movie.javlibraryzh": false,
    "scraper.movie.mgstageja": true,
    "scraper.movie.r18": false,
    "scraper.movie.r18zh": false,
    "scraper.option.dmm.scrapeactress": false,
    "scraper.option.idpreference": "id",
    "match.minimumfilesize": 0,
    "match.includedfileextension": [
        ".asf",
        ".avi",
        ".flv",
        ".m4v",
        ".mkv",
        ".mp4",
        ".mov",
        ".rmvb",
        ".wmv"
    ],
    "match.excludedfilestring": ["^.*-trailer*", "^.*-5\\."],
    "match.regex": 0,
    "match.regex.string": "([a-zA-Z|tT28]+-\\d+[zZ]?[eE]?)(?:-pt)?(\\d{1,2})?",
    "match.regex.idmatch": 1,
    "match.regex.ptmatch": 2,
    "sort.movetofolder": false,
    "sort.renamefile": false,
    "sort.maxtitlelength": 100,
    "sort.create.nfo": true,
    "sort.create.nfoperfile": false,
    "sort.download.actressimg": true,
    "sort.download.thumbimg": true,
    "sort.download.posterimg": false,
    "sort.download.screenshotimg": true,
    "sort.download.trailervid": false,
    "sort.format.groupactress": true,
    "sort.format.delimiter": ", ",
    "sort.format.file": "<ID>",
    "sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)",
    "sort.format.outputfolder": [],
    "sort.format.posterimg": "posster",
    "sort.format.thumbimg": "poster",
    "sort.format.trailervid": "<ID>-trailer",
    "sort.format.nfo": "movie",
    "sort.format.screenshotimg": "fanart-",
    "sort.format.screenshotfolder": "extrafanart",
    "sort.format.actressimgfolder": ".actors",
    "sort.metadata.nfo.mediainfo": false,
    "sort.metadata.nfo.altnamerole": false,
    "sort.metadata.nfo.translate": true,
    "sort.metadata.nfo.translate.module": "google_trans_new",
    "sort.metadata.nfo.translate.field": ["description", "title", "genre", "director", "label", "maker", "series"],
    "sort.metadata.nfo.translate.language": "en",
    "sort.metadata.nfo.displayname": "<ID> - <TITLE>",
    "sort.metadata.nfo.firstnameorder": false,
    "sort.metadata.nfo.actresslanguageja": false,
    "sort.metadata.nfo.unknownactress": true,
    "sort.metadata.nfo.originalpath": false,
    "sort.metadata.nfo.format.tag": ["<SET>"],
    "sort.metadata.nfo.format.tagline": "./",
    "sort.metadata.nfo.format.credits": [],
    "sort.metadata.thumbcsv": true,
    "sort.metadata.thumbcsv.autoadd": true,
    "sort.metadata.thumbcsv.convertalias": true,
    "sort.metadata.genrecsv": false,
    "sort.metadata.genre.ignore": ["^Featured Actress", "^Hi-Def", ".*sale.*"],
    "sort.metadata.requiredfield": ["id", "coverurl", "genre", "maker", "releaseDate", "title"],
    "sort.metadata.priority.actress": ["mgstageja", "javlibrary", "r18", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.alternatetitle": ["dmmja"],
    "sort.metadata.priority.coverurl": ["mgstageja", "r18", "dmmja", "javlibrary", "javbus","mgstageja", "aventertainment"],
    "sort.metadata.priority.description": ["mgstageja", "dmmja", "dmm", "mgstageja", "aventertainment"],
    "sort.metadata.priority.director": ["mgstageja", "r18", "javlibrary", "mgstageja", "aventertainment"],
    "sort.metadata.priority.genre": ["mgstageja", "r18", "javlibrary", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.id": ["mgstageja", "r18", "javlibrary", "javbus","mgstageja", "aventertainment"],
    "sort.metadata.priority.contentid": ["mgstageja", "r18", "dmmja"],
    "sort.metadata.priority.label": ["mgstageja", "r18", "javlibrary", "mgstageja", "aventertainment"],
    "sort.metadata.priority.maker": ["mgstageja", "r18", "javlibrary", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.releasedate": ["mgstageja", "r18", "javlibrary", "dmmja", "javbus","mgstageja", "aventertainment"],
    "sort.metadata.priority.rating": ["mgstageja", "dmmja","mgstageja"],
    "sort.metadata.priority.runtime": ["mgstageja", "r18", "javlibrary", "dmmja", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.series": ["mgstageja", "r18", "r18zh", "mgstageja"],
    "sort.metadata.priority.screenshoturl": ["mgstageja", "r18", "javlibrary", "dmmja", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.title": ["mgstageja", "r18", "javlibrary", "javbus", "mgstageja", "aventertainment"],
    "sort.metadata.priority.trailerurl": ["r18", "dmmja"],
    "emby.url": "http:\/\/192.168.0.1:8096",
    "emby.apikey": "",
    "javlibrary.baseurl": "http:\/\/www.javlibrary.com",
    "javlibrary.browser.useragent": "",
    "javlibrary.cookie.cfduid": "",
    "javlibrary.cookie.cfclearance": "",
    "javlibrary.cookie.session": "",
    "javlibrary.cookie.userid": "",
    "web.sort.recurse": true,
    "web.sort.strict": false,
    "web.sort.interactive": true,
    "web.sort.update": false,
    "web.sort.force": false,
    "web.sort.confirm": false,
    "web.sort.manualsearch.dmm": false,
    "web.sort.manualsearch.dmmja": false,
    "web.sort.manualsearch.jav321ja": false,
    "web.sort.manualsearch.javbus": false,
    "web.sort.manualsearch.javbusja": false,
    "web.sort.manualsearch.javbuszh": false,
    "web.sort.manualsearch.javlibrary": false,
    "web.sort.manualsearch.javlibraryja": false,
    "web.sort.manualsearch.javlibraryzh": false,
    "web.sort.manualsearch.r18": false,
    "web.sort.manualsearch.r18zh": false,
    "web.navigation.pagesize": 5,
    "admin.log": true,
    "admin.log.level": "info"
}
`

I had installed google-trans-new https://github.com/lushan88a/google_trans_new

Running this under Ubuntu 16.04 LTS, powershell 7. 
Python is wonky stuck at 3.5 but I installed manually 3.6 and pip3.

**Comment by jvlflame** [comment]
Is python 3.6 being called from `python3`? Do a `python3 --version`.

Javinizer will run python commands using `python3` on all Linux OS.

**Comment by NewMember12345** [comment]
Python 3.6.3

```
PS /home/glovedbox/Downloads/long.seed/done/1sis> Javinizer ./200GANA-1864/200GA                                                                                                                                                                                                NA-1864.1080p.2048.mp4 -SettingsPath './jvSettings.json' -IsThread
Traceback (most recent call last):
  File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translat                                                                                                                                                                                                e_new.py", line 7, in <module>
    translation = translator.translate(sys.argv[1], dest=sys.argv[2])
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182,                                                                                                                                                                                                 in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78,                                                                                                                                                                                                 in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194,                                                                                                                                                                                                 in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62,                                                                                                                                                                                                 in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
Remove-Item: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:30
Line |
  30 |                  Remove-Item -Path $tempFile -ErrorAction SilentlyCont …
     |                                    ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Get-Content: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:28
Line |
  28 |  …               $translatedString = Get-Content -Path $tempFile -Encodi                                                                                                                                                                                                 …
     |                                                        ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Traceback (most recent call last):
  File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translat                                                                                                                                                                                                e_new.py", line 7, in <module>
    translation = translator.translate(sys.argv[1], dest=sys.argv[2])
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182,                                                                                                                                                                                                 in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78,                                                                                                                                                                                                 in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194,                                                                                                                                                                                                 in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62,                                                                                                                                                                                                 in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
Remove-Item: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:30
Line |
  30 |                  Remove-Item -Path $tempFile -ErrorAction SilentlyCont …
     |                                    ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Get-Content: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:28
Line |
  28 |  …               $translatedString = Get-Content -Path $tempFile -Encodi                                                                                                                                                                                                 …
     |                                                        ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Traceback (most recent call last):
  File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translat                                                                                                                                                                                                e_new.py", line 7, in <module>
    translation = translator.translate(sys.argv[1], dest=sys.argv[2])
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182,                                                                                                                                                                                                 in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78,                                                                                                                                                                                                 in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194,                                                                                                                                                                                                 in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62,                                                                                                                                                                                                 in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
Remove-Item: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:30
Line |
  30 |                  Remove-Item -Path $tempFile -ErrorAction SilentlyCont …
     |                                    ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Get-Content: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:28
Line |
  28 |  …               $translatedString = Get-Content -Path $tempFile -Encodi                                                                                                                                                                                                 …
     |                                                        ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Traceback (most recent call last):
  File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translat                                                                                                                                                                                                e_new.py", line 7, in <module>
    translation = translator.translate(sys.argv[1], dest=sys.argv[2])
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182,                                                                                                                                                                                                 in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78,                                                                                                                                                                                                 in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194,                                                                                                                                                                                                 in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62,                                                                                                                                                                                                 in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
Remove-Item: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:30
Line |
  30 |                  Remove-Item -Path $tempFile -ErrorAction SilentlyCont …
     |                                    ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Get-Content: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:28
Line |
  28 |  …               $translatedString = Get-Content -Path $tempFile -Encodi                                                                                                                                                                                                 …
     |                                                        ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Traceback (most recent call last):
  File "/home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/translat                                                                                                                                                                                                e_new.py", line 7, in <module>
    translation = translator.translate(sys.argv[1], dest=sys.argv[2])
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 182,                                                                                                                                                                                                 in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.6/site-packages/googletrans/client.py", line 78,                                                                                                                                                                                                 in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 194,                                                                                                                                                                                                 in do
    self._update()
  File "/usr/local/lib/python3.6/site-packages/googletrans/gtoken.py", line 62,                                                                                                                                                                                                 in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
Remove-Item: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:30
Line |
  30 |                  Remove-Item -Path $tempFile -ErrorAction SilentlyCont …
     |                                    ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Get-Content: /home/glovedbox/.local/share/powershell/Modules/Javinizer/2.2.0/Pri                                                                                                                                                                                                vate/Get-TranslatedString.ps1:28
Line |
  28 |  …               $translatedString = Get-Content -Path $tempFile -Encodi                                                                                                                                                                                                 …
     |                                                        ~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.
```

**Comment by NewMember12345** [comment]
Okay found my own solution. 

python3 -m pip install googletrans==4.0.0rc1

it was still running 3.0  even though I set the translate module to the google_trans_new - it still wanted the original but updated 4.0rc1.

**Comment by jvlflame** [comment]
Yeah, thanks for this post. I realized I forgot to change the file contents of the `translate_new.py` file after adding it. Javinizer is still using `googletrans` even though it's set to google_trans_new.

I'll push a new build for 2.2.1 to resolve this.
