### ISSUE TITLE
Javinizer GUI Not Loading

### ISSUE THREAD

**Issue by DarkMask100** [jvlflame/Javinizer#183]
Hello,

After following the instructions and installing the Javinizer Web GUI and importing it, it seems an "empty" dashboard is shown as all I see is "Hello World!"

The log shows me the following
```
[01-17-21 12:48:53 AM] PS: One or more errors occurred. (Cannot overwrite variable null because it is read-only or constant.) 
```

I'm also seeing the following in the Universal Server terminal.

```
fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      Error when dispatching 'OnDisconnectedAsync' on hub.
System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalDashboard.DashboardHub.OnDisconnectedAsync(Exception exception) in D:\a\universal\universal\src\Universal.Server\Hubs\DashboardHub.cs:line 58
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
fail: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[3]
      Failed disposing connection Yjw5VhOyAZ7IKBIUdhfNig.
System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalDashboard.DashboardHub.OnDisconnectedAsync(Exception exception) in D:\a\universal\universal\src\Universal.Server\Hubs\DashboardHub.cs:line 58
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.ExecuteApplication(ConnectionDelegate connectionDelegate)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully)
```

Tried removing the module and adding it back but can't seem to get it to show the Web GUI.

**Comment by jvlflame** [comment]
The dashboard file may have accidentally been deleted. If you go on the dashboard info page in the Powershell Universal admin portal, edit the dashboard code and paste in the code from [here](https://raw.githubusercontent.com/jvlflame/Javinizer/master/src/Javinizer/Universal/Repository/javinizergui.ps1).

**Comment by DarkMask100** [comment]
Hello,

Yeah looks like the code was deleted, pasting that code did the trick.

Thank you!
