### ISSUE TITLE
Javlibrary scraper failures

### ISSUE THREAD

**Issue by jvlflame** [jvlflame/Javinizer#41]
Javinizer fails to work when JAVLibrary scraper is turned on.

[This is currently a known bug and will be resolved when the cloudscraper repository is updated to resolve new Cloudflare challenges.](https://github.com/VeNoMouS/cloudscraper/issues)

```
[2020-05-01T19:19:42][Javinizer] Function started
ERROR:root:"http://www.javlibrary.com/en/" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "C:\Users\J\Documents\PowerShell\Modules\Javinizer\1.4.2\cfscraper.py", line 4, in <module>
    cookie_value, user_agent = cloudscraper.get_cookie_string(
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 667, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, **kwargs)
  File "C:\Python38\lib\site-packages\cloudscraper\__init__.py", line 632, in get_tokens
    resp.raise_for_status()
  File "C:\Python38\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: http://www.javlibrary.com/en/
VERBOSE: [2020-05-01T19:19:43][Get-JavlibraryUrl] Search [abp-610] not matched on JAVLibrary
[2020-05-01T19:19:43][Javinizer] Function ended
```

**Comment by jvlflame** [comment]
New update from [cloudscraper](https://github.com/VeNoMouS/cloudscraper/releases) has resolved the issue. 

Update with  ```pip install cloudscraper -U```

**Comment by jvlflame** [comment]
[cloudscraper updated to 1.2.38](https://github.com/VeNoMouS/cloudscraper/releases/tag/1.2.38)
